#!/bin/bash

# Vérifier si l'utilisateur est root
if [ "$EUID" -ne 0 ]
  then echo "Ce script doit être utilisé en tant que root pour avoir les permissions nécessaires d'installation"
  exit
fi

# Installer le client NFS sur la machine
apt -y install nfs-common

# Monter le homedir dans le serveur NFS
cat > /etc/fstab << 'EOL'
192.168.1.5:/home   /home   nfs  noauto,x-systemd.automount   0  0

EOL
mount 192.168.1.5:/home /home
