#!/bin/bash
((count = 1))
((ipDown = 255))
((ipUp = 255))                           # Maximum number to try.
while [[ $ipUp -ne 0 ]] ; do
	while [[ $ipDown -ne 0 ]] ; do
		while [[ $count -ne 0 ]] ; do
    			ping -c 1 192.168.$ipUp.$ipDown                    # Try once.
    			rc=$?
    			if [[ $rc -eq 0 ]] ; then
        			((count = 1))                    # If okay, flag loop exit.
    			else
        			sleep 1                          # Minimise network storm.
    			fi
    			((count = count - 1))                # So we don't go forever.
		done
		if [[ $rc -eq 0 ]] ; then                # Make final determination.
    			echo "The internet is up on 192.168.${ipUp}.${ipDown}"
		else
    			echo "Timeout."
		fi
		((count = 1))
		((ipDown = ipDown - 1))
	done
	((ipDown = 255))
	((ipUp = ipUp - 1))
done
