#!/bin/bash

# Vérifier si l'utilisateur est root
if [ "$EUID" -ne 0 ]
  then echo "Ce script doit être utilisé en tant que root pour avoir les permissions nécessaires d'installation"
  exit
fi

# Install the remote journald packages
apt update
apt upgrade
apt install systemd-journal-remote

# Mettre en marche le client des logs
systemctl enable systemd-journal-upload.service

# Ouverture du port 80 sur le pare-feu