#!/bin/bash

#Lancer ce script en root
#Si l'utilisateur lancant le script n'est pas root, cela affichera un message d'erreur 
if [ $(id -u) -ne 0 ]
then 
   echo "Ce script doit être lancé en tant que root"
   exit 1
fi

if ! dpkg -s isc-dhcp-client > /dev/null 2>&1
then
   echo "Installation du paquet isc-dhcp-client"
   apt -y install isc-dhcp-client
fi

#Réécriture du fichier de configuration des interfaces réseau   
sed -i '$a\# This file describes the network interfaces available on your system\nauto eth0\niface eth0 inet dhcp' "/etc/network/interfaces"

#Redémarrage du service networking
systemctl restart networking.service

#quelle difference entre faire ifdown eth0 && ifup eth0 ??
#personnalisation du script si installion de servers ??
# cat > /etc/network/interfaces << 'EOL'
#auto eth0
#iface eth0 inet static
#address 192.168.0.3
#netmask 255.255.255.0
#gateway 192.168.0.2