#!/bin/bash
#Verifie que le script est lancé en root
if [[ $EUID -ne 0 ]]; then
   echo "Ce script doit être lancé en tant que root" 
   exit 1
fi

#Mettre à jour la liste des paquets
apt -y update
apt -y upgrade

#Installe des paquets isc-dhcp-server
apt -y install isc-dhcp-server

#Modifier
sed -i 's/INTERFACESv4=""/INTERFACESv4="eth0"/g' /etc/default/isc-dhcp-server

#Modifier le fichier de configuration
cat > /etc/dhcp/dhcpd.conf << 'EOL'
#dhcpd.conf
default-lease-time 600;
max-lease-time 7200;
authorative;
#option subnet-mask 255.255.255.0;
option domain-name "cipher.com";
option domain-name-servers 192.168.128.7;

# Subnet pour les postes de travail
subnet 192.168.128.0 netmask 255.255.255.0 {
    range 192.168.128.2 192.168.128.23;
    option routers 192.168.128.1;postgress_server68.128.255;
};

#Subnet pour la DMZ
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.0.2 192.168.0.4;
    option routers 192.168.0.1;
    option broadcast-address 192.168.0.254;
}

#Subnet pour les serveurs
#separé des serveur, malgré le même router ?
subnet 192.168.128.0 netmask 255.255.255.0 {
    range 192.168.128.23 192.168.128.253;
    option routers 192.168.128.1;
    option broadcast-address 192.168.128.254;
}

host ldap_server{
    #remplacer ethernet addresses
    hardware ethernet 08:00:06:21:c1:a2;
    fixed-address ldap.cipher.com;
}

host log_server{
    #remplacer ethernet addresses
    hardware ethernet 08:00:06:21:c1:a2;
    fixed-address log.cipher.com;
}

host postgress_server{
    #remplacer ethernet addresses
    hardware ethernet 08:00:06:21:c1:a2;
    fixed-address postgress.cipher.com;
}



EOL

#Redemarrer le service
service udhcpd restart

#Ajouter le script au démarrage
echo "service udhcpd restart" >> /etc/rc.local