#!/bin/bash
#Verifie que le script est lancé en root
if [[ $EUID -ne 0 ]]; then
   echo "Ce script doit être lancé en tant que root" 
   exit 1
fi

#Mettre à jour la liste des paquets
    apt -y update
    apt -y upgrade

#Installe des paquets isc-dhcp-server
    apt -y install isc-dhcp-server

#Modifier
    sed -i 's/INTERFACESv4=""/INTERFACESv4="eth0"/g' /etc/default/isc-dhcp-server

#Replacer le fichier de configuration par celui present dans le dossier dhcp
    rm /etc/dhcp/dhcpd.conf
    cp dhcpd.conf /etc/dhcp/dhcpd.conf

#Redemarrer le service
    systemctl restart isc-dhcp-server.service

#Ajouter le script au démarrage
    #echo "service udhcpd restart" >> /etc/rc.local