#!/bin/bash

#Lancer ce script en root
#Si l'utilisateur lancant le script n'est pas root, cela affichera un message d'erreur 
if [ $(id -u) -ne 0 ]
then 
   echo "Ce script doit être lancé en tant que root"
   exit 1
fi

# General
apt -y update
apt -y upgrade
mkdir LDAP
cd LDAP


#Installatin des packets slapd nécessaire
apt-get policy slapd -y
	#Saisi du mot de passe administrateur nécessaire dans l'interface graphique
apt -y install slapd

#Creation d'un utilisateur non privilégié 
useradd -r -M -d /var/lib/openldap -s /usr/sbin/nologin ldap

#Installation des dépendances
apt install libsasl2-dev make libtool build-essential openssl \
libevent-dev libargon2-dev sudo wget pkg-config wiredtiger \
libsystemd-dev libssl-dev

#Télechargement de la version 2.6.4  OpenLDAP sur le site du constructeur
wget https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.6.4.tgz

#Extraction du code source
tar xzf openldap-2.6.4.tgz

cd openldap-2.6.4

#Configuratino LDAP :
./configure --prefix=/usr --sysconfdir=/etc --disable-static \
--enable-debug --with-tls=openssl --with-cyrus-sasl \
--enable-dynamic --enable-crypt --enable-spasswd \
--enable-slapd --enable-modules --enable-rlookups \
--enable-backends=mod --disable-sql --enable-ppolicy=mod \
--enable-syslog --enable-overlays=mod --with-systemd --enable-wt=no

#Installer les dépendances
make depend
#Installation du package libperl-dev nécessaire mais pas installé par make depend (?)
apt install libperl-dev

#Compiler OpenLDAP
make
make install

#Creer un repertoire pour la base de données et pour les données LDAP
mkdir /var/lib/openldap /etc/openldap/slapd.d

#Affecter les propriétés et les permissions aux repertoires LDAP
chown -R ldap:ldap /var/lib/openldap
chown root:ldap /etc/openldap/slapd.conf
chmod 640 /etc/openldap/slapd.conf

#Mise à jour du fichier OpenLDAP
mv /lib/systemd/system/slapd.service{,.old}

#Installation du packet sudo-ldap
apt install sudo-ldap

#Copie du schema  :
find /usr/share/doc/ -iname schema.openldap
cp /usr/share/doc/sudo-ldap/schema.OpenLDAP  /etc/openldap/schema/sudo.schema


#Creation du fichier sudo.ldif
cat << 'EOL' > /etc/openldap/schema/sudo.ldif 
dn: cn=sudo,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: sudo
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.1 NAME 'sudoUser' DESC 'User(s) who may  run sudo' EQUALITY caseExactIA5Match SUBSTR caseExactIA5SubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.2 NAME 'sudoHost' DESC 'Host(s) who may run sudo' EQUALITY caseExactIA5Match SUBSTR caseExactIA5SubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.3 NAME 'sudoCommand' DESC 'Command(s) to be executed by sudo' EQUALITY caseExactIA5Match SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.4 NAME 'sudoRunAs' DESC 'User(s) impersonated by sudo (deprecated)' EQUALITY caseExactIA5Match SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.5 NAME 'sudoOption' DESC 'Options(s) followed by sudo' EQUALITY caseExactIA5Match SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.6 NAME 'sudoRunAsUser' DESC 'User(s) impersonated by sudo' EQUALITY caseExactIA5Match SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcAttributeTypes: ( 1.3.6.1.4.1.15953.9.1.7 NAME 'sudoRunAsGroup' DESC 'Group(s) impersonated by sudo' EQUALITY caseExactIA5Match SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
olcObjectClasses: ( 1.3.6.1.4.1.15953.9.2.1 NAME 'sudoRole' SUP top STRUCTURAL DESC 'Sudoer Entries' MUST ( cn ) MAY ( sudoUser $ sudoHost $ sudoCommand $ sudoRunAs $ sudoRunAsUser $ sudoRunAsGroup $ sudoOption $ description ) )
EOL

#Mise à jour de la base de données slapd
mv /etc/openldap/slapd.ldif{,.bak}
cat > /etc/openldap/slapd.ldif << 'EOL'
dn: cn=config
objectClass: olcGlobal
cn: config
olcArgsFile: /var/lib/openldap/slapd.args
olcPidFile: /var/lib/openldap/slapd.pid

dn: cn=schema,cn=config
objectClass: olcSchemaConfig
cn: schema

dn: cn=module,cn=config
objectClass: olcModuleList
cn: module
olcModulepath: /usr/libexec/openldap
olcModuleload: back_mdb.la

include: file:///etc/openldap/schema/core.ldif
include: file:///etc/openldap/schema/cosine.ldif
include: file:///etc/openldap/schema/nis.ldif
include: file:///etc/openldap/schema/inetorgperson.ldif
include: file:///etc/openldap/schema/sudo.ldif
#include: file:///etc/openldap/schema/ppolicy.ldif
dn: olcDatabase=frontend,cn=config
objectClass: olcDatabaseConfig
objectClass: olcFrontendConfig
olcDatabase: frontend
olcAccess: to dn.base="cn=Subschema" by * read
olcAccess: to * 
  by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage 
  by * none

dn: olcDatabase=config,cn=config
objectClass: olcDatabaseConfig
olcDatabase: config
olcRootDN: cn=config
olcAccess: to * 
  by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage 
  by * none
EOL


#Creation of the first database
slapadd -n 0 -F /etc/openldap/slapd.d -l /etc/openldap/slapd.ldif

#Affecter les propriétés du fichier slapd.d à l'utilisateur ldap
chown -R ldap:ldap /etc/openldap/slapd.d


#Relancer systemd et demarrer le service OpenLDAP
systemctl daemon-reload
systemctl enable --now slapd

#Log disponible ici : /var/log/slapd.log








